### ISSUE TITLE
cannot import name 'plot_confusion_matrix'

### ISSUE THREAD

**Issue by batool-ali** [deepfence/FlowMeter#5]
When am attempting to run below command 
`python3 Deepfence_ML_flowmeter.py`
to generate ML parameters and classify packets, I am receiving this error:
``
File "/home/batool/FlowMeter/assets/Deepfence_ML_flowmeter.py", line 24, in <module>
    from sklearn.metrics import (
ImportError: cannot import name 'plot_confusion_matrix' from 'sklearn.metrics' (/home/batool/.local/lib/python3.10/site-packages/sklearn/metrics/__init__.py)
``

How can I fix it please?

**Comment by aniruddhakasar** [comment]
from sklearn.metrics import confusion_matrix 
syntax

**Comment by Prathu122** [comment]
You can use this code for showing the confusion matrix, it will work as intended-
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

# Compute confusion matrix
cm = confusion_matrix(true_labels, predicted_labels)

# Plot confusion matrix
plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues)
plt.title('Confusion Matrix')
plt.colorbar()
tick_marks = np.arange(len(classes))
plt.xticks(tick_marks, classes, rotation=45)
plt.yticks(tick_marks, classes)

fmt = 'd'
thresh = cm.max() / 2.
for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1)):
    plt.text(j, i, format(cm[i, j], fmt),
             horizontalalignment="center",
             color="white" if cm[i, j] > thresh else "black")

plt.ylabel('True label')
plt.xlabel('Predicted label')
plt.show()
